export const response = {
  landingPageId: 0,
  initialTextInput: "Announcing a discount on a Toyota vehicle",
  pdfText:
    "Toyota of Deerfield Beach has made it easy to upgrade to a new Toyota. Since you’re already pre-qualified, you could trade in your 2017 Corolla and get into a new 2019 Corolla with an incredibly low payment and no money out of pocket. BUY WITH CONFIDENCE YOU’RE PRE-QUALIFIED FOR $25,000 2017 Camry (...1024) With your 2017 Corolla trade-in. Excludes tax, tag, registration and title. This offer applies to well-qualified buyers and requires (1) trade-in of 2017 Toyota Corolla VIN 8675309 and (2) approved credit and financing through Southeast Toyota Finance, with a minimum amount financed of $7,500 and maximum amount financed equal to the new vehicle MSRP or the prequalified amounts stated above, whichever is less. Credit offer valid only for the addressee and may be withdrawn if it is found that you no longer meet the criteria established by Southeast Toyota Finance. Excludes tax, tag, registration and title; includes dealer fee of $50.00. Dealer Discount must be used toward the purchase of vehicles shown above. Bonus Cash must be used toward purchase. May be combined with certain other offers. See dealer for complete details. Must complete retail sale and take delivery between 10/1/2019 and 12/31/2019. With your 2017 Corolla trade-in. Excludes tax, tag, registration and title.",
  pdfFileName: "landing page w-mobile.pdf",
  extractedCompanies: ["Toyota of Deerfield Beach, Southeast Toyota Finance"],
  extractedBrands: ["Toyota"],
  pdfImages: [
    {
      imageUrl:
        "https://assets.ctfassets.net/da02ousowwa0/6XrW98XnVkPMfew7HANBGP/5c5d060f61ea75dd660ed547f20556e7/Image0.png",
      imageAltText: "Image0",
    },
    {
      imageUrl: "https://source.unsplash.com/random/900%C3%97700/?toyota",
      imageAltText: "Toyota",
    },
  ],
  landingPage: {
    hero: {
      title: "Upgrade to a New 2019 Corolla with Ease",
      shortDescription:
        "Upgrade to a new Toyota at Toyota of Deerfield Beach with low payments and no money out of pocket.",
      imageUrl: "https://source.unsplash.com/random/900%C3%9900/?toyota",
      imageAltText: "toyota",
      buttonText: "Upgrade Now!",
      buttonUrl:
        "https://assets.ctfassets.net/da02ousowwa0/68ss9L6cavMydGYK9Y3oeA/913e68cb2193568007515d681ff02b73/landing_page_w-mobile.pdf",
    },
  },
  companyInfo: {
    entryTitle: "Toyota Company Info",
    fullCompanyName: "Toyota Motor Corporation",
    shortCompanyName: "Toyota",
    copyright: "Copyright 2023 Toyota Motor Corporation",
    companyUrl: "https://www.toyota.com",
    companyLogo: {
      systemProperties: {
        id: "LLNbscdDrdqUQX277UF5p",
        linkType: null,
        type: "Asset",
        revision: 1,
        version: null,
        createdAt: "2023-08-02T02:56:33.382Z",
        createdBy: null,
        updatedAt: "2023-08-02T02:56:33.382Z",
        updatedBy: null,
        deletedAt: null,
        locale: "en-US",
        contentType: null,
        space: {
          systemProperties: {
            id: "da02ousowwa0",
            linkType: "Space",
            type: "Link",
            revision: null,
            version: null,
            createdAt: null,
            createdBy: null,
            updatedAt: null,
            updatedBy: null,
            deletedAt: null,
            locale: null,
            contentType: null,
            space: null,
            publishedCounter: null,
            publishedVersion: null,
            publishedBy: null,
            publishedAt: null,
            publishCounter: null,
            firstPublishedAt: null,
            archivedAt: null,
            archivedVersion: null,
            archivedBy: null,
            status: null,
            environment: null,
            organization: null,
            usagePeriod: null,
          },
          name: null,
          locales: null,
        },
        publishedCounter: null,
        publishedVersion: null,
        publishedBy: null,
        publishedAt: null,
        publishCounter: null,
        firstPublishedAt: null,
        archivedAt: null,
        archivedVersion: null,
        archivedBy: null,
        status: null,
        environment: {
          systemProperties: {
            id: "master",
            linkType: "Environment",
            type: "Link",
            revision: null,
            version: null,
            createdAt: null,
            createdBy: null,
            updatedAt: null,
            updatedBy: null,
            deletedAt: null,
            locale: null,
            contentType: null,
            space: null,
            publishedCounter: null,
            publishedVersion: null,
            publishedBy: null,
            publishedAt: null,
            publishCounter: null,
            firstPublishedAt: null,
            archivedAt: null,
            archivedVersion: null,
            archivedBy: null,
            status: null,
            environment: null,
            organization: null,
            usagePeriod: null,
          },
        },
        organization: null,
        usagePeriod: null,
      },
      description: "",
      title: "ToyotaLogoRedVer",
      file: {
        fileName: "ToyotaLogoRedVer.svg",
        contentType: "image/svg+xml",
        url: "//images.ctfassets.net/da02ousowwa0/LLNbscdDrdqUQX277UF5p/3282752c81bc15111cdd50a1c0e6bdc4/ToyotaLogoRedVer.svg",
        uploadUrl: null,
        uploadReference: null,
        details: { size: 6309, image: { height: 672, width: 935 } },
      },
      titleLocalized: { "en-US": "ToyotaLogoRedVer" },
      descriptionLocalized: { "en-US": "" },
      filesLocalized: {
        "en-US": {
          fileName: "ToyotaLogoRedVer.svg",
          contentType: "image/svg+xml",
          url: "//images.ctfassets.net/da02ousowwa0/LLNbscdDrdqUQX277UF5p/3282752c81bc15111cdd50a1c0e6bdc4/ToyotaLogoRedVer.svg",
          uploadUrl: null,
          uploadReference: null,
          details: { size: 6309, image: { height: 672, width: 935 } },
        },
      },
      metadata: { tags: [] },
    },
  },
};
