import "./globals.css";
import type { Metadata } from "next";
import { Inter, Roboto_Mono, Titillium_Web } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});

const titillium_web = Titillium_Web({
  subsets: ["latin"],
  weight: ["200", "400", "600", "700"],
  display: "swap",
  variable: "--font-titillium-web",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.style} ${roboto_mono.variable} ${titillium_web.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
